<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function getRouteKeyName()
    {
        return ('name'); // TODO: Change the autogenerated stub
    }
}
